name: CI

permissions: { checks: write, actions: read, contents: read }

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x

      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: Build develop bundle
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build:prod` command
      - name: Lint the app
        uses: borales/actions-yarn@v4
        with:
          cmd: lint # will run `yarn test` command

      - name: Cypress run
        uses: cypress-io/github-action@v4.1.0
        with:
          config-file: cypress.config.ts
          browser: chrome
          build: yarn build
          start: yarn dev
          wait-on: 'http://localhost:5173'
          config: baseUrl=http://localhost:5173
          spec: cypress/e2e/homepage.cy.ts
